# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://open-archive.net
title: OpenArchive
email: info@open-archive.net
author: NatalieC510
description: > # 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/open_archive
  - title: github
    url: https://github.com/openarchive
 
